[package]
name = "pdfgen"
version = "0.1.0"
edition = "2021"

[dependencies]
docx = "1.1.2"
jetscii = "0.5.3"
jsonpath_lib = "0.3.0"
printpdf = "0.7.0"
reqwest = "0.12.5"
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0.124"
tokio = "1.39.2"
